/* ======================================================================
   data.js  –  Complete world trivia data (all 195 countries)
   Flags (ISO codes), Capitals, Continents, Languages & Currencies
   ====================================================================== */

const TRIVIA_DATA = {

  /* ---------- FLAGS ---------- */
  flags: [
    { country: "Afghanistan", code: "af" },
    { country: "Albania", code: "al" },
    { country: "Algeria", code: "dz" },
    { country: "Andorra", code: "ad" },
    { country: "Angola", code: "ao" },
    { country: "Antigua and Barbuda", code: "ag" },
    { country: "Argentina", code: "ar" },
    { country: "Armenia", code: "am" },
    { country: "Australia", code: "au" },
    { country: "Austria", code: "at" },
    { country: "Azerbaijan", code: "az" },
    { country: "Bahamas", code: "bs" },
    { country: "Bahrain", code: "bh" },
    { country: "Bangladesh", code: "bd" },
    { country: "Barbados", code: "bb" },
    { country: "Belarus", code: "by" },
    { country: "Belgium", code: "be" },
    { country: "Belize", code: "bz" },
    { country: "Benin", code: "bj" },
    { country: "Bhutan", code: "bt" },
    { country: "Bolivia", code: "bo" },
    { country: "Bosnia and Herzegovina", code: "ba" },
    { country: "Botswana", code: "bw" },
    { country: "Brazil", code: "br" },
    { country: "Brunei", code: "bn" },
    { country: "Bulgaria", code: "bg" },
    { country: "Burkina Faso", code: "bf" },
    { country: "Burundi", code: "bi" },
    { country: "Cabo Verde", code: "cv" },
    { country: "Cambodia", code: "kh" },
    { country: "Cameroon", code: "cm" },
    { country: "Canada", code: "ca" },
    { country: "Central African Republic", code: "cf" },
    { country: "Chad", code: "td" },
    { country: "Chile", code: "cl" },
    { country: "China", code: "cn" },
    { country: "Colombia", code: "co" },
    { country: "Comoros", code: "km" },
    { country: "Congo (DRC)", code: "cd" },
    { country: "Congo (Republic)", code: "cg" },
    { country: "Costa Rica", code: "cr" },
    { country: "Côte d'Ivoire", code: "ci" },
    { country: "Croatia", code: "hr" },
    { country: "Cuba", code: "cu" },
    { country: "Cyprus", code: "cy" },
    { country: "Czech Republic", code: "cz" },
    { country: "Denmark", code: "dk" },
    { country: "Djibouti", code: "dj" },
    { country: "Dominica", code: "dm" },
    { country: "Dominican Republic", code: "do" },
    { country: "Ecuador", code: "ec" },
    { country: "Egypt", code: "eg" },
    { country: "El Salvador", code: "sv" },
    { country: "Equatorial Guinea", code: "gq" },
    { country: "Eritrea", code: "er" },
    { country: "Estonia", code: "ee" },
    { country: "Eswatini", code: "sz" },
    { country: "Ethiopia", code: "et" },
    { country: "Fiji", code: "fj" },
    { country: "Finland", code: "fi" },
    { country: "France", code: "fr" },
    { country: "Gabon", code: "ga" },
    { country: "Gambia", code: "gm" },
    { country: "Georgia", code: "ge" },
    { country: "Germany", code: "de" },
    { country: "Ghana", code: "gh" },
    { country: "Greece", code: "gr" },
    { country: "Grenada", code: "gd" },
    { country: "Guatemala", code: "gt" },
    { country: "Guinea", code: "gn" },
    { country: "Guinea-Bissau", code: "gw" },
    { country: "Guyana", code: "gy" },
    { country: "Haiti", code: "ht" },
    { country: "Honduras", code: "hn" },
    { country: "Hungary", code: "hu" },
    { country: "Iceland", code: "is" },
    { country: "India", code: "in" },
    { country: "Indonesia", code: "id" },
    { country: "Iran", code: "ir" },
    { country: "Iraq", code: "iq" },
    { country: "Ireland", code: "ie" },
    { country: "Israel", code: "il" },
    { country: "Italy", code: "it" },
    { country: "Jamaica", code: "jm" },
    { country: "Japan", code: "jp" },
    { country: "Jordan", code: "jo" },
    { country: "Kazakhstan", code: "kz" },
    { country: "Kenya", code: "ke" },
    { country: "Kiribati", code: "ki" },
    { country: "Kosovo", code: "xk" },
    { country: "Kuwait", code: "kw" },
    { country: "Kyrgyzstan", code: "kg" },
    { country: "Laos", code: "la" },
    { country: "Latvia", code: "lv" },
    { country: "Lebanon", code: "lb" },
    { country: "Lesotho", code: "ls" },
    { country: "Liberia", code: "lr" },
    { country: "Libya", code: "ly" },
    { country: "Liechtenstein", code: "li" },
    { country: "Lithuania", code: "lt" },
    { country: "Luxembourg", code: "lu" },
    { country: "Madagascar", code: "mg" },
    { country: "Malawi", code: "mw" },
    { country: "Malaysia", code: "my" },
    { country: "Maldives", code: "mv" },
    { country: "Mali", code: "ml" },
    { country: "Malta", code: "mt" },
    { country: "Marshall Islands", code: "mh" },
    { country: "Mauritania", code: "mr" },
    { country: "Mauritius", code: "mu" },
    { country: "Mexico", code: "mx" },
    { country: "Micronesia", code: "fm" },
    { country: "Moldova", code: "md" },
    { country: "Monaco", code: "mc" },
    { country: "Mongolia", code: "mn" },
    { country: "Montenegro", code: "me" },
    { country: "Morocco", code: "ma" },
    { country: "Mozambique", code: "mz" },
    { country: "Myanmar", code: "mm" },
    { country: "Namibia", code: "na" },
    { country: "Nauru", code: "nr" },
    { country: "Nepal", code: "np" },
    { country: "Netherlands", code: "nl" },
    { country: "New Zealand", code: "nz" },
    { country: "Nicaragua", code: "ni" },
    { country: "Niger", code: "ne" },
    { country: "Nigeria", code: "ng" },
    { country: "North Korea", code: "kp" },
    { country: "North Macedonia", code: "mk" },
    { country: "Norway", code: "no" },
    { country: "Oman", code: "om" },
    { country: "Pakistan", code: "pk" },
    { country: "Palau", code: "pw" },
    { country: "Palestine", code: "ps" },
    { country: "Panama", code: "pa" },
    { country: "Papua New Guinea", code: "pg" },
    { country: "Paraguay", code: "py" },
    { country: "Peru", code: "pe" },
    { country: "Philippines", code: "ph" },
    { country: "Poland", code: "pl" },
    { country: "Portugal", code: "pt" },
    { country: "Qatar", code: "qa" },
    { country: "Romania", code: "ro" },
    { country: "Russia", code: "ru" },
    { country: "Rwanda", code: "rw" },
    { country: "Saint Kitts and Nevis", code: "kn" },
    { country: "Saint Lucia", code: "lc" },
    { country: "Saint Vincent and the Grenadines", code: "vc" },
    { country: "Samoa", code: "ws" },
    { country: "San Marino", code: "sm" },
    { country: "São Tomé and Príncipe", code: "st" },
    { country: "Saudi Arabia", code: "sa" },
    { country: "Senegal", code: "sn" },
    { country: "Serbia", code: "rs" },
    { country: "Seychelles", code: "sc" },
    { country: "Sierra Leone", code: "sl" },
    { country: "Singapore", code: "sg" },
    { country: "Slovakia", code: "sk" },
    { country: "Slovenia", code: "si" },
    { country: "Solomon Islands", code: "sb" },
    { country: "Somalia", code: "so" },
    { country: "South Africa", code: "za" },
    { country: "South Korea", code: "kr" },
    { country: "South Sudan", code: "ss" },
    { country: "Spain", code: "es" },
    { country: "Sri Lanka", code: "lk" },
    { country: "Sudan", code: "sd" },
    { country: "Suriname", code: "sr" },
    { country: "Sweden", code: "se" },
    { country: "Switzerland", code: "ch" },
    { country: "Syria", code: "sy" },
    { country: "Taiwan", code: "tw" },
    { country: "Tajikistan", code: "tj" },
    { country: "Tanzania", code: "tz" },
    { country: "Thailand", code: "th" },
    { country: "Timor-Leste", code: "tl" },
    { country: "Togo", code: "tg" },
    { country: "Tonga", code: "to" },
    { country: "Trinidad and Tobago", code: "tt" },
    { country: "Tunisia", code: "tn" },
    { country: "Turkey", code: "tr" },
    { country: "Turkmenistan", code: "tm" },
    { country: "Tuvalu", code: "tv" },
    { country: "Uganda", code: "ug" },
    { country: "Ukraine", code: "ua" },
    { country: "United Arab Emirates", code: "ae" },
    { country: "United Kingdom", code: "gb" },
    { country: "United States", code: "us" },
    { country: "Uruguay", code: "uy" },
    { country: "Uzbekistan", code: "uz" },
    { country: "Vanuatu", code: "vu" },
    { country: "Vatican City", code: "va" },
    { country: "Venezuela", code: "ve" },
    { country: "Vietnam", code: "vn" },
    { country: "Yemen", code: "ye" },
    { country: "Zambia", code: "zm" },
    { country: "Zimbabwe", code: "zw" },
  ],

  /* ---------- COUNTRIES (capitals & continents) ---------- */
  countries: [
    { country: "Afghanistan", capital: "Kabul", continent: "Asia" },
    { country: "Albania", capital: "Tirana", continent: "Europe" },
    { country: "Algeria", capital: "Algiers", continent: "Africa" },
    { country: "Andorra", capital: "Andorra la Vella", continent: "Europe" },
    { country: "Angola", capital: "Luanda", continent: "Africa" },
    { country: "Antigua and Barbuda", capital: "St. John's", continent: "North America" },
    { country: "Argentina", capital: "Buenos Aires", continent: "South America" },
    { country: "Armenia", capital: "Yerevan", continent: "Asia" },
    { country: "Australia", capital: "Canberra", continent: "Oceania" },
    { country: "Austria", capital: "Vienna", continent: "Europe" },
    { country: "Azerbaijan", capital: "Baku", continent: "Asia" },
    { country: "Bahamas", capital: "Nassau", continent: "North America" },
    { country: "Bahrain", capital: "Manama", continent: "Asia" },
    { country: "Bangladesh", capital: "Dhaka", continent: "Asia" },
    { country: "Barbados", capital: "Bridgetown", continent: "North America" },
    { country: "Belarus", capital: "Minsk", continent: "Europe" },
    { country: "Belgium", capital: "Brussels", continent: "Europe" },
    { country: "Belize", capital: "Belmopan", continent: "North America" },
    { country: "Benin", capital: "Porto-Novo", continent: "Africa" },
    { country: "Bhutan", capital: "Thimphu", continent: "Asia" },
    { country: "Bolivia", capital: "Sucre", continent: "South America" },
    { country: "Bosnia and Herzegovina", capital: "Sarajevo", continent: "Europe" },
    { country: "Botswana", capital: "Gaborone", continent: "Africa" },
    { country: "Brazil", capital: "Brasília", continent: "South America" },
    { country: "Brunei", capital: "Bandar Seri Begawan", continent: "Asia" },
    { country: "Bulgaria", capital: "Sofia", continent: "Europe" },
    { country: "Burkina Faso", capital: "Ouagadougou", continent: "Africa" },
    { country: "Burundi", capital: "Gitega", continent: "Africa" },
    { country: "Cabo Verde", capital: "Praia", continent: "Africa" },
    { country: "Cambodia", capital: "Phnom Penh", continent: "Asia" },
    { country: "Cameroon", capital: "Yaoundé", continent: "Africa" },
    { country: "Canada", capital: "Ottawa", continent: "North America" },
    { country: "Central African Republic", capital: "Bangui", continent: "Africa" },
    { country: "Chad", capital: "N'Djamena", continent: "Africa" },
    { country: "Chile", capital: "Santiago", continent: "South America" },
    { country: "China", capital: "Beijing", continent: "Asia" },
    { country: "Colombia", capital: "Bogotá", continent: "South America" },
    { country: "Comoros", capital: "Moroni", continent: "Africa" },
    { country: "Congo (DRC)", capital: "Kinshasa", continent: "Africa" },
    { country: "Congo (Republic)", capital: "Brazzaville", continent: "Africa" },
    { country: "Costa Rica", capital: "San José", continent: "North America" },
    { country: "Côte d'Ivoire", capital: "Yamoussoukro", continent: "Africa" },
    { country: "Croatia", capital: "Zagreb", continent: "Europe" },
    { country: "Cuba", capital: "Havana", continent: "North America" },
    { country: "Cyprus", capital: "Nicosia", continent: "Europe" },
    { country: "Czech Republic", capital: "Prague", continent: "Europe" },
    { country: "Denmark", capital: "Copenhagen", continent: "Europe" },
    { country: "Djibouti", capital: "Djibouti", continent: "Africa" },
    { country: "Dominica", capital: "Roseau", continent: "North America" },
    { country: "Dominican Republic", capital: "Santo Domingo", continent: "North America" },
    { country: "Ecuador", capital: "Quito", continent: "South America" },
    { country: "Egypt", capital: "Cairo", continent: "Africa" },
    { country: "El Salvador", capital: "San Salvador", continent: "North America" },
    { country: "Equatorial Guinea", capital: "Malabo", continent: "Africa" },
    { country: "Eritrea", capital: "Asmara", continent: "Africa" },
    { country: "Estonia", capital: "Tallinn", continent: "Europe" },
    { country: "Eswatini", capital: "Mbabane", continent: "Africa" },
    { country: "Ethiopia", capital: "Addis Ababa", continent: "Africa" },
    { country: "Fiji", capital: "Suva", continent: "Oceania" },
    { country: "Finland", capital: "Helsinki", continent: "Europe" },
    { country: "France", capital: "Paris", continent: "Europe" },
    { country: "Gabon", capital: "Libreville", continent: "Africa" },
    { country: "Gambia", capital: "Banjul", continent: "Africa" },
    { country: "Georgia", capital: "Tbilisi", continent: "Asia" },
    { country: "Germany", capital: "Berlin", continent: "Europe" },
    { country: "Ghana", capital: "Accra", continent: "Africa" },
    { country: "Greece", capital: "Athens", continent: "Europe" },
    { country: "Grenada", capital: "St. George's", continent: "North America" },
    { country: "Guatemala", capital: "Guatemala City", continent: "North America" },
    { country: "Guinea", capital: "Conakry", continent: "Africa" },
    { country: "Guinea-Bissau", capital: "Bissau", continent: "Africa" },
    { country: "Guyana", capital: "Georgetown", continent: "South America" },
    { country: "Haiti", capital: "Port-au-Prince", continent: "North America" },
    { country: "Honduras", capital: "Tegucigalpa", continent: "North America" },
    { country: "Hungary", capital: "Budapest", continent: "Europe" },
    { country: "Iceland", capital: "Reykjavik", continent: "Europe" },
    { country: "India", capital: "New Delhi", continent: "Asia" },
    { country: "Indonesia", capital: "Jakarta", continent: "Asia" },
    { country: "Iran", capital: "Tehran", continent: "Asia" },
    { country: "Iraq", capital: "Baghdad", continent: "Asia" },
    { country: "Ireland", capital: "Dublin", continent: "Europe" },
    { country: "Israel", capital: "Jerusalem", continent: "Asia" },
    { country: "Italy", capital: "Rome", continent: "Europe" },
    { country: "Jamaica", capital: "Kingston", continent: "North America" },
    { country: "Japan", capital: "Tokyo", continent: "Asia" },
    { country: "Jordan", capital: "Amman", continent: "Asia" },
    { country: "Kazakhstan", capital: "Astana", continent: "Asia" },
    { country: "Kenya", capital: "Nairobi", continent: "Africa" },
    { country: "Kiribati", capital: "Tarawa", continent: "Oceania" },
    { country: "Kosovo", capital: "Pristina", continent: "Europe" },
    { country: "Kuwait", capital: "Kuwait City", continent: "Asia" },
    { country: "Kyrgyzstan", capital: "Bishkek", continent: "Asia" },
    { country: "Laos", capital: "Vientiane", continent: "Asia" },
    { country: "Latvia", capital: "Riga", continent: "Europe" },
    { country: "Lebanon", capital: "Beirut", continent: "Asia" },
    { country: "Lesotho", capital: "Maseru", continent: "Africa" },
    { country: "Liberia", capital: "Monrovia", continent: "Africa" },
    { country: "Libya", capital: "Tripoli", continent: "Africa" },
    { country: "Liechtenstein", capital: "Vaduz", continent: "Europe" },
    { country: "Lithuania", capital: "Vilnius", continent: "Europe" },
    { country: "Luxembourg", capital: "Luxembourg City", continent: "Europe" },
    { country: "Madagascar", capital: "Antananarivo", continent: "Africa" },
    { country: "Malawi", capital: "Lilongwe", continent: "Africa" },
    { country: "Malaysia", capital: "Kuala Lumpur", continent: "Asia" },
    { country: "Maldives", capital: "Malé", continent: "Asia" },
    { country: "Mali", capital: "Bamako", continent: "Africa" },
    { country: "Malta", capital: "Valletta", continent: "Europe" },
    { country: "Marshall Islands", capital: "Majuro", continent: "Oceania" },
    { country: "Mauritania", capital: "Nouakchott", continent: "Africa" },
    { country: "Mauritius", capital: "Port Louis", continent: "Africa" },
    { country: "Mexico", capital: "Mexico City", continent: "North America" },
    { country: "Micronesia", capital: "Palikir", continent: "Oceania" },
    { country: "Moldova", capital: "Chișinău", continent: "Europe" },
    { country: "Monaco", capital: "Monaco", continent: "Europe" },
    { country: "Mongolia", capital: "Ulaanbaatar", continent: "Asia" },
    { country: "Montenegro", capital: "Podgorica", continent: "Europe" },
    { country: "Morocco", capital: "Rabat", continent: "Africa" },
    { country: "Mozambique", capital: "Maputo", continent: "Africa" },
    { country: "Myanmar", capital: "Naypyidaw", continent: "Asia" },
    { country: "Namibia", capital: "Windhoek", continent: "Africa" },
    { country: "Nauru", capital: "Yaren", continent: "Oceania" },
    { country: "Nepal", capital: "Kathmandu", continent: "Asia" },
    { country: "Netherlands", capital: "Amsterdam", continent: "Europe" },
    { country: "New Zealand", capital: "Wellington", continent: "Oceania" },
    { country: "Nicaragua", capital: "Managua", continent: "North America" },
    { country: "Niger", capital: "Niamey", continent: "Africa" },
    { country: "Nigeria", capital: "Abuja", continent: "Africa" },
    { country: "North Korea", capital: "Pyongyang", continent: "Asia" },
    { country: "North Macedonia", capital: "Skopje", continent: "Europe" },
    { country: "Norway", capital: "Oslo", continent: "Europe" },
    { country: "Oman", capital: "Muscat", continent: "Asia" },
    { country: "Pakistan", capital: "Islamabad", continent: "Asia" },
    { country: "Palau", capital: "Ngerulmud", continent: "Oceania" },
    { country: "Palestine", capital: "Ramallah", continent: "Asia" },
    { country: "Panama", capital: "Panama City", continent: "North America" },
    { country: "Papua New Guinea", capital: "Port Moresby", continent: "Oceania" },
    { country: "Paraguay", capital: "Asunción", continent: "South America" },
    { country: "Peru", capital: "Lima", continent: "South America" },
    { country: "Philippines", capital: "Manila", continent: "Asia" },
    { country: "Poland", capital: "Warsaw", continent: "Europe" },
    { country: "Portugal", capital: "Lisbon", continent: "Europe" },
    { country: "Qatar", capital: "Doha", continent: "Asia" },
    { country: "Romania", capital: "Bucharest", continent: "Europe" },
    { country: "Russia", capital: "Moscow", continent: "Europe" },
    { country: "Rwanda", capital: "Kigali", continent: "Africa" },
    { country: "Saint Kitts and Nevis", capital: "Basseterre", continent: "North America" },
    { country: "Saint Lucia", capital: "Castries", continent: "North America" },
    { country: "Saint Vincent and the Grenadines", capital: "Kingstown", continent: "North America" },
    { country: "Samoa", capital: "Apia", continent: "Oceania" },
    { country: "San Marino", capital: "San Marino", continent: "Europe" },
    { country: "São Tomé and Príncipe", capital: "São Tomé", continent: "Africa" },
    { country: "Saudi Arabia", capital: "Riyadh", continent: "Asia" },
    { country: "Senegal", capital: "Dakar", continent: "Africa" },
    { country: "Serbia", capital: "Belgrade", continent: "Europe" },
    { country: "Seychelles", capital: "Victoria", continent: "Africa" },
    { country: "Sierra Leone", capital: "Freetown", continent: "Africa" },
    { country: "Singapore", capital: "Singapore", continent: "Asia" },
    { country: "Slovakia", capital: "Bratislava", continent: "Europe" },
    { country: "Slovenia", capital: "Ljubljana", continent: "Europe" },
    { country: "Solomon Islands", capital: "Honiara", continent: "Oceania" },
    { country: "Somalia", capital: "Mogadishu", continent: "Africa" },
    { country: "South Africa", capital: "Pretoria", continent: "Africa" },
    { country: "South Korea", capital: "Seoul", continent: "Asia" },
    { country: "South Sudan", capital: "Juba", continent: "Africa" },
    { country: "Spain", capital: "Madrid", continent: "Europe" },
    { country: "Sri Lanka", capital: "Sri Jayawardenepura Kotte", continent: "Asia" },
    { country: "Sudan", capital: "Khartoum", continent: "Africa" },
    { country: "Suriname", capital: "Paramaribo", continent: "South America" },
    { country: "Sweden", capital: "Stockholm", continent: "Europe" },
    { country: "Switzerland", capital: "Bern", continent: "Europe" },
    { country: "Syria", capital: "Damascus", continent: "Asia" },
    { country: "Taiwan", capital: "Taipei", continent: "Asia" },
    { country: "Tajikistan", capital: "Dushanbe", continent: "Asia" },
    { country: "Tanzania", capital: "Dodoma", continent: "Africa" },
    { country: "Thailand", capital: "Bangkok", continent: "Asia" },
    { country: "Timor-Leste", capital: "Dili", continent: "Asia" },
    { country: "Togo", capital: "Lomé", continent: "Africa" },
    { country: "Tonga", capital: "Nukuʻalofa", continent: "Oceania" },
    { country: "Trinidad and Tobago", capital: "Port of Spain", continent: "North America" },
    { country: "Tunisia", capital: "Tunis", continent: "Africa" },
    { country: "Turkey", capital: "Ankara", continent: "Asia" },
    { country: "Turkmenistan", capital: "Ashgabat", continent: "Asia" },
    { country: "Tuvalu", capital: "Funafuti", continent: "Oceania" },
    { country: "Uganda", capital: "Kampala", continent: "Africa" },
    { country: "Ukraine", capital: "Kyiv", continent: "Europe" },
    { country: "United Arab Emirates", capital: "Abu Dhabi", continent: "Asia" },
    { country: "United Kingdom", capital: "London", continent: "Europe" },
    { country: "United States", capital: "Washington, D.C.", continent: "North America" },
    { country: "Uruguay", capital: "Montevideo", continent: "South America" },
    { country: "Uzbekistan", capital: "Tashkent", continent: "Asia" },
    { country: "Vanuatu", capital: "Port Vila", continent: "Oceania" },
    { country: "Vatican City", capital: "Vatican City", continent: "Europe" },
    { country: "Venezuela", capital: "Caracas", continent: "South America" },
    { country: "Vietnam", capital: "Hanoi", continent: "Asia" },
    { country: "Yemen", capital: "Sana'a", continent: "Asia" },
    { country: "Zambia", capital: "Lusaka", continent: "Africa" },
    { country: "Zimbabwe", capital: "Harare", continent: "Africa" },
  ],

  /* ---------- LANGUAGES ---------- */
  languages: [
    { country: "Afghanistan", language: "Pashto & Dari" },
    { country: "Albania", language: "Albanian" },
    { country: "Algeria", language: "Arabic & Berber" },
    { country: "Andorra", language: "Catalan" },
    { country: "Angola", language: "Portuguese" },
    { country: "Antigua and Barbuda", language: "English" },
    { country: "Argentina", language: "Spanish" },
    { country: "Armenia", language: "Armenian" },
    { country: "Australia", language: "English" },
    { country: "Austria", language: "German" },
    { country: "Azerbaijan", language: "Azerbaijani" },
    { country: "Bahamas", language: "English" },
    { country: "Bahrain", language: "Arabic" },
    { country: "Bangladesh", language: "Bengali" },
    { country: "Barbados", language: "English" },
    { country: "Belarus", language: "Belarusian & Russian" },
    { country: "Belgium", language: "Dutch, French & German" },
    { country: "Belize", language: "English" },
    { country: "Benin", language: "French" },
    { country: "Bhutan", language: "Dzongkha" },
    { country: "Bolivia", language: "Spanish" },
    { country: "Bosnia and Herzegovina", language: "Bosnian, Croatian & Serbian" },
    { country: "Botswana", language: "English & Setswana" },
    { country: "Brazil", language: "Portuguese" },
    { country: "Brunei", language: "Malay" },
    { country: "Bulgaria", language: "Bulgarian" },
    { country: "Burkina Faso", language: "French" },
    { country: "Burundi", language: "Kirundi & French" },
    { country: "Cabo Verde", language: "Portuguese" },
    { country: "Cambodia", language: "Khmer" },
    { country: "Cameroon", language: "French & English" },
    { country: "Canada", language: "English & French" },
    { country: "Central African Republic", language: "French & Sango" },
    { country: "Chad", language: "French & Arabic" },
    { country: "Chile", language: "Spanish" },
    { country: "China", language: "Mandarin Chinese" },
    { country: "Colombia", language: "Spanish" },
    { country: "Comoros", language: "Comorian, Arabic & French" },
    { country: "Congo (DRC)", language: "French" },
    { country: "Congo (Republic)", language: "French" },
    { country: "Costa Rica", language: "Spanish" },
    { country: "Côte d'Ivoire", language: "French" },
    { country: "Croatia", language: "Croatian" },
    { country: "Cuba", language: "Spanish" },
    { country: "Cyprus", language: "Greek & Turkish" },
    { country: "Czech Republic", language: "Czech" },
    { country: "Denmark", language: "Danish" },
    { country: "Djibouti", language: "French & Arabic" },
    { country: "Dominica", language: "English" },
    { country: "Dominican Republic", language: "Spanish" },
    { country: "Ecuador", language: "Spanish" },
    { country: "Egypt", language: "Arabic" },
    { country: "El Salvador", language: "Spanish" },
    { country: "Equatorial Guinea", language: "Spanish, French & Portuguese" },
    { country: "Eritrea", language: "Tigrinya & Arabic" },
    { country: "Estonia", language: "Estonian" },
    { country: "Eswatini", language: "English & Swazi" },
    { country: "Ethiopia", language: "Amharic" },
    { country: "Fiji", language: "English, Fijian & Hindi" },
    { country: "Finland", language: "Finnish & Swedish" },
    { country: "France", language: "French" },
    { country: "Gabon", language: "French" },
    { country: "Gambia", language: "English" },
    { country: "Georgia", language: "Georgian" },
    { country: "Germany", language: "German" },
    { country: "Ghana", language: "English" },
    { country: "Greece", language: "Greek" },
    { country: "Grenada", language: "English" },
    { country: "Guatemala", language: "Spanish" },
    { country: "Guinea", language: "French" },
    { country: "Guinea-Bissau", language: "Portuguese" },
    { country: "Guyana", language: "English" },
    { country: "Haiti", language: "French & Haitian Creole" },
    { country: "Honduras", language: "Spanish" },
    { country: "Hungary", language: "Hungarian" },
    { country: "Iceland", language: "Icelandic" },
    { country: "India", language: "Hindi & English" },
    { country: "Indonesia", language: "Indonesian" },
    { country: "Iran", language: "Persian (Farsi)" },
    { country: "Iraq", language: "Arabic & Kurdish" },
    { country: "Ireland", language: "English & Irish" },
    { country: "Israel", language: "Hebrew & Arabic" },
    { country: "Italy", language: "Italian" },
    { country: "Jamaica", language: "English" },
    { country: "Japan", language: "Japanese" },
    { country: "Jordan", language: "Arabic" },
    { country: "Kazakhstan", language: "Kazakh & Russian" },
    { country: "Kenya", language: "Swahili & English" },
    { country: "Kiribati", language: "English & Gilbertese" },
    { country: "Kosovo", language: "Albanian & Serbian" },
    { country: "Kuwait", language: "Arabic" },
    { country: "Kyrgyzstan", language: "Kyrgyz & Russian" },
    { country: "Laos", language: "Lao" },
    { country: "Latvia", language: "Latvian" },
    { country: "Lebanon", language: "Arabic" },
    { country: "Lesotho", language: "Sesotho & English" },
    { country: "Liberia", language: "English" },
    { country: "Libya", language: "Arabic" },
    { country: "Liechtenstein", language: "German" },
    { country: "Lithuania", language: "Lithuanian" },
    { country: "Luxembourg", language: "Luxembourgish, French & German" },
    { country: "Madagascar", language: "Malagasy & French" },
    { country: "Malawi", language: "English & Chichewa" },
    { country: "Malaysia", language: "Malay" },
    { country: "Maldives", language: "Dhivehi" },
    { country: "Mali", language: "French" },
    { country: "Malta", language: "Maltese & English" },
    { country: "Marshall Islands", language: "Marshallese & English" },
    { country: "Mauritania", language: "Arabic" },
    { country: "Mauritius", language: "English & French" },
    { country: "Mexico", language: "Spanish" },
    { country: "Micronesia", language: "English" },
    { country: "Moldova", language: "Romanian" },
    { country: "Monaco", language: "French" },
    { country: "Mongolia", language: "Mongolian" },
    { country: "Montenegro", language: "Montenegrin" },
    { country: "Morocco", language: "Arabic & Berber" },
    { country: "Mozambique", language: "Portuguese" },
    { country: "Myanmar", language: "Burmese" },
    { country: "Namibia", language: "English" },
    { country: "Nauru", language: "Nauruan & English" },
    { country: "Nepal", language: "Nepali" },
    { country: "Netherlands", language: "Dutch" },
    { country: "New Zealand", language: "English & Māori" },
    { country: "Nicaragua", language: "Spanish" },
    { country: "Niger", language: "French" },
    { country: "Nigeria", language: "English" },
    { country: "North Korea", language: "Korean" },
    { country: "North Macedonia", language: "Macedonian" },
    { country: "Norway", language: "Norwegian" },
    { country: "Oman", language: "Arabic" },
    { country: "Pakistan", language: "Urdu & English" },
    { country: "Palau", language: "Palauan & English" },
    { country: "Palestine", language: "Arabic" },
    { country: "Panama", language: "Spanish" },
    { country: "Papua New Guinea", language: "English, Tok Pisin & Hiri Motu" },
    { country: "Paraguay", language: "Spanish & Guaraní" },
    { country: "Peru", language: "Spanish" },
    { country: "Philippines", language: "Filipino & English" },
    { country: "Poland", language: "Polish" },
    { country: "Portugal", language: "Portuguese" },
    { country: "Qatar", language: "Arabic" },
    { country: "Romania", language: "Romanian" },
    { country: "Russia", language: "Russian" },
    { country: "Rwanda", language: "Kinyarwanda, French & English" },
    { country: "Saint Kitts and Nevis", language: "English" },
    { country: "Saint Lucia", language: "English" },
    { country: "Saint Vincent and the Grenadines", language: "English" },
    { country: "Samoa", language: "Samoan & English" },
    { country: "San Marino", language: "Italian" },
    { country: "São Tomé and Príncipe", language: "Portuguese" },
    { country: "Saudi Arabia", language: "Arabic" },
    { country: "Senegal", language: "French" },
    { country: "Serbia", language: "Serbian" },
    { country: "Seychelles", language: "Seychellois Creole, English & French" },
    { country: "Sierra Leone", language: "English" },
    { country: "Singapore", language: "English, Malay, Mandarin & Tamil" },
    { country: "Slovakia", language: "Slovak" },
    { country: "Slovenia", language: "Slovene" },
    { country: "Solomon Islands", language: "English" },
    { country: "Somalia", language: "Somali & Arabic" },
    { country: "South Africa", language: "Zulu, Xhosa, Afrikaans & English" },
    { country: "South Korea", language: "Korean" },
    { country: "South Sudan", language: "English" },
    { country: "Spain", language: "Spanish" },
    { country: "Sri Lanka", language: "Sinhala & Tamil" },
    { country: "Sudan", language: "Arabic & English" },
    { country: "Suriname", language: "Dutch" },
    { country: "Sweden", language: "Swedish" },
    { country: "Switzerland", language: "German, French, Italian & Romansh" },
    { country: "Syria", language: "Arabic" },
    { country: "Taiwan", language: "Mandarin Chinese" },
    { country: "Tajikistan", language: "Tajik" },
    { country: "Tanzania", language: "Swahili & English" },
    { country: "Thailand", language: "Thai" },
    { country: "Timor-Leste", language: "Portuguese & Tetum" },
    { country: "Togo", language: "French" },
    { country: "Tonga", language: "Tongan & English" },
    { country: "Trinidad and Tobago", language: "English" },
    { country: "Tunisia", language: "Arabic" },
    { country: "Turkey", language: "Turkish" },
    { country: "Turkmenistan", language: "Turkmen" },
    { country: "Tuvalu", language: "Tuvaluan & English" },
    { country: "Uganda", language: "English & Swahili" },
    { country: "Ukraine", language: "Ukrainian" },
    { country: "United Arab Emirates", language: "Arabic" },
    { country: "United Kingdom", language: "English" },
    { country: "United States", language: "English" },
    { country: "Uruguay", language: "Spanish" },
    { country: "Uzbekistan", language: "Uzbek" },
    { country: "Vanuatu", language: "Bislama, English & French" },
    { country: "Vatican City", language: "Italian & Latin" },
    { country: "Venezuela", language: "Spanish" },
    { country: "Vietnam", language: "Vietnamese" },
    { country: "Yemen", language: "Arabic" },
    { country: "Zambia", language: "English" },
    { country: "Zimbabwe", language: "English, Shona & Ndebele" },
  ],

  /* ---------- CURRENCIES ---------- */
  currencies: [
    { country: "Afghanistan", currency: "Afghan Afghani (؋)" },
    { country: "Albania", currency: "Albanian Lek (L)" },
    { country: "Algeria", currency: "Algerian Dinar (د.ج)" },
    { country: "Andorra", currency: "Euro (€)" },
    { country: "Angola", currency: "Angolan Kwanza (Kz)" },
    { country: "Antigua and Barbuda", currency: "East Caribbean Dollar (EC$)" },
    { country: "Argentina", currency: "Argentine Peso (ARS)" },
    { country: "Armenia", currency: "Armenian Dram (֏)" },
    { country: "Australia", currency: "Australian Dollar (A$)" },
    { country: "Austria", currency: "Euro (€)" },
    { country: "Azerbaijan", currency: "Azerbaijani Manat (₼)" },
    { country: "Bahamas", currency: "Bahamian Dollar (B$)" },
    { country: "Bahrain", currency: "Bahraini Dinar (BD)" },
    { country: "Bangladesh", currency: "Bangladeshi Taka (৳)" },
    { country: "Barbados", currency: "Barbadian Dollar (Bds$)" },
    { country: "Belarus", currency: "Belarusian Ruble (Br)" },
    { country: "Belgium", currency: "Euro (€)" },
    { country: "Belize", currency: "Belize Dollar (BZ$)" },
    { country: "Benin", currency: "West African CFA Franc (CFA)" },
    { country: "Bhutan", currency: "Bhutanese Ngultrum (Nu)" },
    { country: "Bolivia", currency: "Bolivian Boliviano (Bs)" },
    { country: "Bosnia and Herzegovina", currency: "Convertible Mark (KM)" },
    { country: "Botswana", currency: "Botswana Pula (P)" },
    { country: "Brazil", currency: "Brazilian Real (R$)" },
    { country: "Brunei", currency: "Brunei Dollar (B$)" },
    { country: "Bulgaria", currency: "Bulgarian Lev (лв)" },
    { country: "Burkina Faso", currency: "West African CFA Franc (CFA)" },
    { country: "Burundi", currency: "Burundian Franc (FBu)" },
    { country: "Cabo Verde", currency: "Cape Verdean Escudo (CVE)" },
    { country: "Cambodia", currency: "Cambodian Riel (៛)" },
    { country: "Cameroon", currency: "Central African CFA Franc (FCFA)" },
    { country: "Canada", currency: "Canadian Dollar (C$)" },
    { country: "Central African Republic", currency: "Central African CFA Franc (FCFA)" },
    { country: "Chad", currency: "Central African CFA Franc (FCFA)" },
    { country: "Chile", currency: "Chilean Peso (CLP)" },
    { country: "China", currency: "Chinese Yuan (¥)" },
    { country: "Colombia", currency: "Colombian Peso (COP)" },
    { country: "Comoros", currency: "Comorian Franc (CF)" },
    { country: "Congo (DRC)", currency: "Congolese Franc (FC)" },
    { country: "Congo (Republic)", currency: "Central African CFA Franc (FCFA)" },
    { country: "Costa Rica", currency: "Costa Rican Colón (₡)" },
    { country: "Côte d'Ivoire", currency: "West African CFA Franc (CFA)" },
    { country: "Croatia", currency: "Euro (€)" },
    { country: "Cuba", currency: "Cuban Peso (CUP)" },
    { country: "Cyprus", currency: "Euro (€)" },
    { country: "Czech Republic", currency: "Czech Koruna (Kč)" },
    { country: "Denmark", currency: "Danish Krone (kr)" },
    { country: "Djibouti", currency: "Djiboutian Franc (Fdj)" },
    { country: "Dominica", currency: "East Caribbean Dollar (EC$)" },
    { country: "Dominican Republic", currency: "Dominican Peso (RD$)" },
    { country: "Ecuador", currency: "US Dollar ($)" },
    { country: "Egypt", currency: "Egyptian Pound (E£)" },
    { country: "El Salvador", currency: "US Dollar ($)" },
    { country: "Equatorial Guinea", currency: "Central African CFA Franc (FCFA)" },
    { country: "Eritrea", currency: "Eritrean Nakfa (Nfk)" },
    { country: "Estonia", currency: "Euro (€)" },
    { country: "Eswatini", currency: "Swazi Lilangeni (E)" },
    { country: "Ethiopia", currency: "Ethiopian Birr (Br)" },
    { country: "Fiji", currency: "Fijian Dollar (FJ$)" },
    { country: "Finland", currency: "Euro (€)" },
    { country: "France", currency: "Euro (€)" },
    { country: "Gabon", currency: "Central African CFA Franc (FCFA)" },
    { country: "Gambia", currency: "Gambian Dalasi (D)" },
    { country: "Georgia", currency: "Georgian Lari (₾)" },
    { country: "Germany", currency: "Euro (€)" },
    { country: "Ghana", currency: "Ghanaian Cedi (₵)" },
    { country: "Greece", currency: "Euro (€)" },
    { country: "Grenada", currency: "East Caribbean Dollar (EC$)" },
    { country: "Guatemala", currency: "Guatemalan Quetzal (Q)" },
    { country: "Guinea", currency: "Guinean Franc (FG)" },
    { country: "Guinea-Bissau", currency: "West African CFA Franc (CFA)" },
    { country: "Guyana", currency: "Guyanese Dollar (G$)" },
    { country: "Haiti", currency: "Haitian Gourde (G)" },
    { country: "Honduras", currency: "Honduran Lempira (L)" },
    { country: "Hungary", currency: "Hungarian Forint (Ft)" },
    { country: "Iceland", currency: "Icelandic Króna (kr)" },
    { country: "India", currency: "Indian Rupee (₹)" },
    { country: "Indonesia", currency: "Indonesian Rupiah (Rp)" },
    { country: "Iran", currency: "Iranian Rial (﷼)" },
    { country: "Iraq", currency: "Iraqi Dinar (ع.د)" },
    { country: "Ireland", currency: "Euro (€)" },
    { country: "Israel", currency: "Israeli Shekel (₪)" },
    { country: "Italy", currency: "Euro (€)" },
    { country: "Jamaica", currency: "Jamaican Dollar (J$)" },
    { country: "Japan", currency: "Japanese Yen (¥)" },
    { country: "Jordan", currency: "Jordanian Dinar (JD)" },
    { country: "Kazakhstan", currency: "Kazakhstani Tenge (₸)" },
    { country: "Kenya", currency: "Kenyan Shilling (KSh)" },
    { country: "Kiribati", currency: "Australian Dollar (A$)" },
    { country: "Kosovo", currency: "Euro (€)" },
    { country: "Kuwait", currency: "Kuwaiti Dinar (KD)" },
    { country: "Kyrgyzstan", currency: "Kyrgyzstani Som (сом)" },
    { country: "Laos", currency: "Lao Kip (₭)" },
    { country: "Latvia", currency: "Euro (€)" },
    { country: "Lebanon", currency: "Lebanese Pound (ل.ل)" },
    { country: "Lesotho", currency: "Lesotho Loti (L)" },
    { country: "Liberia", currency: "Liberian Dollar (L$)" },
    { country: "Libya", currency: "Libyan Dinar (LD)" },
    { country: "Liechtenstein", currency: "Swiss Franc (CHF)" },
    { country: "Lithuania", currency: "Euro (€)" },
    { country: "Luxembourg", currency: "Euro (€)" },
    { country: "Madagascar", currency: "Malagasy Ariary (Ar)" },
    { country: "Malawi", currency: "Malawian Kwacha (MK)" },
    { country: "Malaysia", currency: "Malaysian Ringgit (RM)" },
    { country: "Maldives", currency: "Maldivian Rufiyaa (Rf)" },
    { country: "Mali", currency: "West African CFA Franc (CFA)" },
    { country: "Malta", currency: "Euro (€)" },
    { country: "Marshall Islands", currency: "US Dollar ($)" },
    { country: "Mauritania", currency: "Mauritanian Ouguiya (UM)" },
    { country: "Mauritius", currency: "Mauritian Rupee (₨)" },
    { country: "Mexico", currency: "Mexican Peso (MX$)" },
    { country: "Micronesia", currency: "US Dollar ($)" },
    { country: "Moldova", currency: "Moldovan Leu (L)" },
    { country: "Monaco", currency: "Euro (€)" },
    { country: "Mongolia", currency: "Mongolian Tögrög (₮)" },
    { country: "Montenegro", currency: "Euro (€)" },
    { country: "Morocco", currency: "Moroccan Dirham (MAD)" },
    { country: "Mozambique", currency: "Mozambican Metical (MT)" },
    { country: "Myanmar", currency: "Myanmar Kyat (K)" },
    { country: "Namibia", currency: "Namibian Dollar (N$)" },
    { country: "Nauru", currency: "Australian Dollar (A$)" },
    { country: "Nepal", currency: "Nepalese Rupee (Rs)" },
    { country: "Netherlands", currency: "Euro (€)" },
    { country: "New Zealand", currency: "New Zealand Dollar (NZ$)" },
    { country: "Nicaragua", currency: "Nicaraguan Córdoba (C$)" },
    { country: "Niger", currency: "West African CFA Franc (CFA)" },
    { country: "Nigeria", currency: "Nigerian Naira (₦)" },
    { country: "North Korea", currency: "North Korean Won (₩)" },
    { country: "North Macedonia", currency: "Macedonian Denar (ден)" },
    { country: "Norway", currency: "Norwegian Krone (kr)" },
    { country: "Oman", currency: "Omani Rial (﷼)" },
    { country: "Pakistan", currency: "Pakistani Rupee (₨)" },
    { country: "Palau", currency: "US Dollar ($)" },
    { country: "Palestine", currency: "Israeli Shekel (₪)" },
    { country: "Panama", currency: "Panamanian Balboa (B/.)" },
    { country: "Papua New Guinea", currency: "Papua New Guinean Kina (K)" },
    { country: "Paraguay", currency: "Paraguayan Guaraní (₲)" },
    { country: "Peru", currency: "Peruvian Sol (S/.)" },
    { country: "Philippines", currency: "Philippine Peso (₱)" },
    { country: "Poland", currency: "Polish Złoty (zł)" },
    { country: "Portugal", currency: "Euro (€)" },
    { country: "Qatar", currency: "Qatari Riyal (QR)" },
    { country: "Romania", currency: "Romanian Leu (lei)" },
    { country: "Russia", currency: "Russian Ruble (₽)" },
    { country: "Rwanda", currency: "Rwandan Franc (RF)" },
    { country: "Saint Kitts and Nevis", currency: "East Caribbean Dollar (EC$)" },
    { country: "Saint Lucia", currency: "East Caribbean Dollar (EC$)" },
    { country: "Saint Vincent and the Grenadines", currency: "East Caribbean Dollar (EC$)" },
    { country: "Samoa", currency: "Samoan Tālā (WS$)" },
    { country: "San Marino", currency: "Euro (€)" },
    { country: "São Tomé and Príncipe", currency: "São Tomé Dobra (Db)" },
    { country: "Saudi Arabia", currency: "Saudi Riyal (﷼)" },
    { country: "Senegal", currency: "West African CFA Franc (CFA)" },
    { country: "Serbia", currency: "Serbian Dinar (din)" },
    { country: "Seychelles", currency: "Seychellois Rupee (₨)" },
    { country: "Sierra Leone", currency: "Sierra Leonean Leone (Le)" },
    { country: "Singapore", currency: "Singapore Dollar (S$)" },
    { country: "Slovakia", currency: "Euro (€)" },
    { country: "Slovenia", currency: "Euro (€)" },
    { country: "Solomon Islands", currency: "Solomon Islands Dollar (SI$)" },
    { country: "Somalia", currency: "Somali Shilling (Sh)" },
    { country: "South Africa", currency: "South African Rand (R)" },
    { country: "South Korea", currency: "South Korean Won (₩)" },
    { country: "South Sudan", currency: "South Sudanese Pound (SSP)" },
    { country: "Spain", currency: "Euro (€)" },
    { country: "Sri Lanka", currency: "Sri Lankan Rupee (Rs)" },
    { country: "Sudan", currency: "Sudanese Pound (SDG)" },
    { country: "Suriname", currency: "Surinamese Dollar (SRD)" },
    { country: "Sweden", currency: "Swedish Krona (kr)" },
    { country: "Switzerland", currency: "Swiss Franc (CHF)" },
    { country: "Syria", currency: "Syrian Pound (£S)" },
    { country: "Taiwan", currency: "New Taiwan Dollar (NT$)" },
    { country: "Tajikistan", currency: "Tajikistani Somoni (SM)" },
    { country: "Tanzania", currency: "Tanzanian Shilling (TSh)" },
    { country: "Thailand", currency: "Thai Baht (฿)" },
    { country: "Timor-Leste", currency: "US Dollar ($)" },
    { country: "Togo", currency: "West African CFA Franc (CFA)" },
    { country: "Tonga", currency: "Tongan Paʻanga (T$)" },
    { country: "Trinidad and Tobago", currency: "Trinidad and Tobago Dollar (TT$)" },
    { country: "Tunisia", currency: "Tunisian Dinar (DT)" },
    { country: "Turkey", currency: "Turkish Lira (₺)" },
    { country: "Turkmenistan", currency: "Turkmenistani Manat (T)" },
    { country: "Tuvalu", currency: "Australian Dollar (A$)" },
    { country: "Uganda", currency: "Ugandan Shilling (USh)" },
    { country: "Ukraine", currency: "Ukrainian Hryvnia (₴)" },
    { country: "United Arab Emirates", currency: "UAE Dirham (AED)" },
    { country: "United Kingdom", currency: "Pound Sterling (£)" },
    { country: "United States", currency: "US Dollar ($)" },
    { country: "Uruguay", currency: "Uruguayan Peso (UYU)" },
    { country: "Uzbekistan", currency: "Uzbekistani Soʻm (сўм)" },
    { country: "Vanuatu", currency: "Vanuatu Vatu (VT)" },
    { country: "Vatican City", currency: "Euro (€)" },
    { country: "Venezuela", currency: "Venezuelan Bolívar (Bs.F)" },
    { country: "Vietnam", currency: "Vietnamese Dong (₫)" },
    { country: "Yemen", currency: "Yemeni Rial (﷼)" },
    { country: "Zambia", currency: "Zambian Kwacha (ZK)" },
    { country: "Zimbabwe", currency: "Zimbabwean Dollar (ZWL)" },
  ],
};
